[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/blog.html"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/projects.html"
  to = "/projects"
  status = 301
  force = true

[[redirects]]
  from = "/api/recent-posts"
  to = "/.netlify/functions/recent-posts"
  status = 200
  force = true

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200
  force = true

[[redirects]]
  from = "/projects"
  to = "/projects.html"
  status = 200
  force = true
