/**
 * Generates sitemap.xml and robots.txt from js/config/routes.js.
 *
 *   node scripts/generate-sitemap.mjs
 *
 * Runs as the Netlify build command, so the sitemap can never drift from the
 * route registry. Both outputs are committed too, so the site still ships a
 * valid sitemap if the build step is ever removed.
 */

import { execFileSync } from 'child_process';
import { statSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

import { SITE, indexableRoutes, DISALLOWED_PATHS, canonicalUrl } from '../js/config/routes.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Last commit that touched the file, falling back to mtime outside a git
 * checkout. Commit date is the honest answer: it is when the page actually
 * changed, not when the deploy happened. Telling Google every page changed on
 * every deploy trains it to ignore lastmod.
 */
function lastModified(relativeFile) {
    const absolute = join(root, relativeFile);

    try {
        const iso = execFileSync('git', ['log', '-1', '--format=%cI', '--', absolute], {
            cwd: root,
            encoding: 'utf8',
            stdio: ['ignore', 'pipe', 'ignore'],
        }).trim();

        if (iso) {
            return iso.slice(0, 10);
        }
    } catch {
        // git missing or not a repository — mtime is good enough
    }

    return statSync(absolute).mtime.toISOString().slice(0, 10);
}

function buildSitemap() {
    const entries = indexableRoutes.map(route => [
        '  <url>',
        `    <loc>${canonicalUrl(route.path)}</loc>`,
        `    <lastmod>${lastModified(route.file)}</lastmod>`,
        `    <changefreq>${route.sitemap.changefreq}</changefreq>`,
        `    <priority>${route.sitemap.priority}</priority>`,
        '  </url>',
    ].join('\n'));

    return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        ...entries,
        '</urlset>',
        '',
    ].join('\n');
}

function buildRobots() {
    return [
        '# Generated by scripts/generate-sitemap.mjs — do not edit by hand.',
        '',
        'User-agent: *',
        'Allow: /',
        '',
        '# Dev artefacts that are reachable but are not part of the site.',
        ...DISALLOWED_PATHS.map(path => `Disallow: ${path}`),
        '',
        `Sitemap: ${SITE.origin}/sitemap.xml`,
        '',
    ].join('\n');
}

writeFileSync(join(root, 'sitemap.xml'), buildSitemap());
writeFileSync(join(root, 'robots.txt'), buildRobots());

console.log(`sitemap.xml: ${indexableRoutes.length} URLs on ${SITE.origin}`);
console.log(`robots.txt: ${DISALLOWED_PATHS.length} disallowed paths`);
